default: true

# Разрешить строки длиннее 80 символов. Редакторы сейчас достаточно умные, что не приходится это делать вручную.
# Чтение этих файлов с помощью vim в терминале не предполагается. :)
MD013: false

# Стиль нумерованных списков
MD029:
  # Либо везде единички (1. 1.), либо по порядку
  style: ordered

# Данная настройка контролирует, сколько пробелов должно быть после обозначения списка
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1

  # В данном случае, мы хотим указать, что в нумерованном списке, где присутствует несколько строк, мы хотим 2 пробела
  # Потому что шаг отступа, который использую я, это 2 пробела.
  # А обозначение нумерованного списка занимает 2 символа. + 1 символ пробела.
  # В результате, получается, что для списка с несколькими строками, у меня вложенные элементы на 1 пробел дальше, чем первая строка.
  # Например, плохо:
  # 1. Первая строка
  # 
  #     Вторая строка
  #
  # Как надо:
  # 1.  Первая строка
  #
  #     Вторая строка
  ol_multi: 2

# HTML-теги
MD033:
  # Разрешить использование некоторых тегов HTML
  allowed_elements:
    # Якори. Используются для списка сокращений
    - a
    # Принудительное закрытие предыдущего блока. Костыль.
    - br
    # Изображения
    - img
    # Аббревиатуры
    - abbr
    # Раскрываемые блоки (споилеры)
    - details
    - summary
    # Клавиши
    - kbd
    # Разрешить span для цветного текста
    - span
    # Если, например, захочется пометить цветом и жирным какой-либо текст, то придётся использовать HTML-разметку
    - b
    - i
    - s
    - em
    - strong
    # Этими вообще по другому в GitHub Flavoured Markdown не воспользоваться
    - sup
    - sub

# Выставить обозначение курсивного текста на _нижние подчёркивания_.
# Чтобы MarkdownLint подсвечивал это как проблему
MD049:
  style: underscore

# Выставить обозначение жирного текста через **звёздочки**
# Чтобы MarkdownLint подсвечивал это как проблему
MD050:
  style: asterisk
